DROP TABLE IF EXISTS sedan;
DROP TABLE IF EXISTS minivan;
DROP TABLE IF EXISTS truck;
DROP TABLE IF EXISTS car_type;

CREATE TABLE car_type
(
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO car_type VALUES (1, 'SEDAN');
INSERT INTO car_type VALUES (2, 'TRUCK');
INSERT INTO car_type VALUES (3, 'MINIVAN');

CREATE TABLE sedan (
                     id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                     brand VARCHAR NOT NULL,
                     model VARCHAR NOT NULL,
                     year BIGINT NOT NULL,
                     car_type_id BIGINT NOT NULL,
                     car_type_name VARCHAR NOT NULL,
                     price NUMERIC(10, 2) NOT NULL,
                     trunk_capacity FLOAT,
                     FOREIGN KEY (car_type_id) REFERENCES car_type(id)
);

CREATE TABLE minivan (
                       id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       brand VARCHAR NOT NULL,
                       model VARCHAR NOT NULL,
                       year BIGINT NOT NULL,
                       car_type_id BIGINT NOT NULL,
                       car_type_name VARCHAR NOT NULL,
                       price NUMERIC(10, 2) NOT NULL,
                       seating_capacity FLOAT,
                       FOREIGN KEY (car_type_id) REFERENCES car_type(id)
);

CREATE TABLE truck (
                         id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         brand VARCHAR NOT NULL,
                         model VARCHAR NOT NULL,
                         year BIGINT NOT NULL,
                         car_type_id BIGINT NOT NULL,
                         car_type_name VARCHAR NOT NULL,
                         price NUMERIC(10, 2) NOT NULL,
                         load_capacity FLOAT,
                         FOREIGN KEY (car_type_id) REFERENCES car_type(id)
);

INSERT INTO sedan VALUES (100,'Chevrolet', 'COLODADO', 2010, 1, 'SEDAN',
                          25000.0,456.0);

INSERT INTO minivan VALUES (100,'Chevrolet', 'MINIVAN', 2010, 2, 'MINIVAN',
                          35000.0,456.0);

INSERT INTO truck VALUES (100,'Chevrolet', 'Tachoe', 2010, 3, 'TRUCK',
                            35000.0,456.0);

SELECT * FROM sedan;
SELECT * FROM minivan;
SELECT * FROM truck;
