DROP TABLE IF EXISTS sedan;
DROP TABLE IF EXISTS minivan;
DROP TABLE IF EXISTS truck;
DROP TABLE IF EXISTS car_type;

CREATE TABLE sedan (
                     id SERIAL PRIMARY KEY NOT NULL,
                     brand VARCHAR NOT NULL,
                     model VARCHAR NOT NULL,
                     year BIGINT NOT NULL,
                     car_type VARCHAR(100) NOT NULL,
                     car_type_id INTEGER NOT NULL,
                     price DOUBLE PRECISION NOT NULL,
                     trunk_capacity DOUBLE PRECISION
);

CREATE TABLE minivan (
                       id SERIAL PRIMARY KEY NOT NULL,
                       brand VARCHAR NOT NULL,
                       model VARCHAR NOT NULL,
                       year BIGINT NOT NULL,
                       car_type VARCHAR(100) NOT NULL,
                       car_type_id INTEGER NOT NULL,
                       price DOUBLE PRECISION NOT NULL,
                       seating_capacity DOUBLE PRECISION
);

CREATE TABLE truck (
                         id SERIAL PRIMARY KEY NOT NULL,
                         brand VARCHAR NOT NULL,
                         model VARCHAR NOT NULL,
                         year BIGINT NOT NULL,
                         car_type VARCHAR(100) NOT NULL,
                         car_type_id INTEGER NOT NULL,
                         price DOUBLE PRECISION NOT NULL,
                         load_capacity DOUBLE PRECISION
);

CREATE TABLE car_type
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

INSERT INTO car_type VALUES (1, 'SEDAN');
INSERT INTO car_type VALUES (2, 'TRUCK');
INSERT INTO car_type VALUES (3, 'MINIVAN');


INSERT INTO sedan VALUES (1,'Chevrolet', 'COLODADO', 2010, 'SEDAN',
                        25000.0,456.0);

INSERT INTO minivan VALUES (1,'Chevrolet', 'MINIVAN', 2010, 'TRUCK',
                          35000.0,456.0);

INSERT INTO truck VALUES (1,'Chevrolet', 'Tachoe', 2010, 'MINIVAN',
                            35000.0,456.0);

SELECT * FROM sedan;
SELECT * FROM minivan;
SELECT * FROM truck;


