DROP DATABASE cardealer_db;
CREATE DATABASE cardealer_db;

DROP TABLE IF EXISTS sedan;
DROP TABLE IF EXISTS minivan;
DROP TABLE IF EXISTS truck;
DROP TABLE IF EXISTS car_type;
DROP TABLE IF EXISTS databasechangelog CASCADE;
DROP TABLE IF EXISTS databasechangeloglock CASCADE;

CREATE TABLE car_type
(
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO car_type VALUES (1, 'SEDAN');
INSERT INTO car_type VALUES (2, 'TRUCK');
INSERT INTO car_type VALUES (3, 'MINIVAN');

CREATE TABLE sedan (
                     id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                     brand VARCHAR NOT NULL,
                     model VARCHAR NOT NULL,
                     year BIGINT NOT NULL,
                     car_type_id BIGINT NOT NULL,
                     price NUMERIC(10, 2) NOT NULL,
                     trunk_capacity FLOAT,
                     FOREIGN KEY (car_type_id) REFERENCES car_type(id)
);

CREATE TABLE minivan (
                       id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       brand VARCHAR NOT NULL,
                       model VARCHAR NOT NULL,
                       year BIGINT NOT NULL,
                       car_type_id BIGINT NOT NULL,
                       price NUMERIC(10, 2) NOT NULL,
                       seating_capacity FLOAT,
                       FOREIGN KEY (car_type_id) REFERENCES car_type(id)
);

CREATE TABLE truck (
                         id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         brand VARCHAR NOT NULL,
                         model VARCHAR NOT NULL,
                         year BIGINT NOT NULL,
                         car_type_id BIGINT NOT NULL,
                         price NUMERIC(10, 2) NOT NULL,
                         load_capacity FLOAT,
                         FOREIGN KEY (car_type_id) REFERENCES car_type(id)
);

INSERT INTO sedan VALUES (101,'Chevrolet', 'COLODADO', 2010, 1,
                          25000.0,456.0);

INSERT INTO truck VALUES (100,'Chevrolet', 'Tachoe', 2010, 2,
                          35000.0,456.0);

INSERT INTO minivan VALUES (100,'Chevrolet', 'MINIVAN', 2010, 3,
                          35000.0,8.0);

SELECT * FROM sedan;
SELECT * FROM minivan;
SELECT * FROM truck;

CREATE INDEX idx_sedan_brand ON sedan (brand);
CREATE INDEX idx_sedan_model ON sedan (model);
CREATE INDEX idx_sedan_year ON sedan (year);
CREATE INDEX idx_sedan_price ON sedan (price);
CREATE INDEX idx_sedan_brand_model ON sedan (brand, model);

CREATE INDEX idx_truck_brand ON truck (brand);
CREATE INDEX idx_truck_model ON truck (model);
CREATE INDEX idx_truck_year ON truck (year);
CREATE INDEX idx_truck_price ON truck (price);
CREATE INDEX idx_truck_brand_model ON truck (brand, model);

CREATE INDEX idx_minivan_brand ON minivan (brand);
CREATE INDEX idx_minivan_model ON minivan (model);
CREATE INDEX idx_minivan_year ON minivan (year);
CREATE INDEX idx_minivan_price ON minivan (price);
CREATE INDEX idx_minivan_brand_model ON minivan (brand, model);

